language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

script:
  - rustc --version
  - cargo --version
  - cargo build --verbose
  - cargo test --verbose
  # Ensure README is synchronized
  - cargo install cargo-sync-readme
  - cargo sync-readme -c -f bin
